dlight-js/dlight

apps/example/src/index.ts, apps/test/CHANGELOG.md, apps/test/package.json, packages/ecosystem/components/CHANGELOG.md, packages/ecosystem/components/package.json, packages/ecosystem/components/src/Router/Route.view.ts
@dlight/component add lazyLoad to Router
=> feat: add lazyLoad to Router

packages/tools/create-dlightjs/src/index.ts, packages/tools/create-dlightjs/templates/dlight-vite-js/index.html, packages/tools/create-dlightjs/templates/dlight-vite-min-js/index.html, packages/tools/create-dlightjs/templates/dlight-vite-min-ts/index.html, packages/tools/create-dlightjs/templates/dlight-vite-ts/index.html
in this pr i added support for `bun` as a package manager option when installing via `create dlightjs` 
and added viewport meta tag for better mobile experience
=> Template features

pnpm-lock.yaml
* **PR #95** 👈
* **PR #96**
* **PR #97**
* **PR #98**
* **PR #99**
=> chore: update to pnpm 9.x and bring lockfile up to date

packages/tools/babel-plugin-syntax-typescript-new/package.json
* **PR #96** 👈
* **PR #97**
* **PR #98**
* **PR #99**
=> chore: update babel-plugin-syntax-typescript-new build to also output cjs

apps/dev/package.json, apps/dev/vite.config.ts
* **PR #97** 👈
* **PR #98**
* **PR #99**
=> chore: update apps/dev example vite and dependencies

apps/ToDoMVC/package.json, apps/ToDoMVC/vite.config.ts
=> chore: update apps/ToDoMVC example vite and dependencies

package.json, packages/core/babel-preset-dlight/package.json, packages/core/dlight/package.json, packages/core/store/package.json, packages/core/transpiler/reactivity-parser/package.json, packages/core/transpiler/view-generator/package.json, packages/core/transpiler/view-parser/package.json, packages/tools/babel-plugin-optional-this/package.json, packages/tools/babel-plugin-syntax-typescript-new/package.json, packages/tools/create-dlightjs/package.json, packages/tools/error-handler/package.json, packages/tools/eslint-plugin-dlight/package.json, packages/tools/vite-plugin-dlight-js/package.json, packages/tools/vite-plugin-dlight/package.json, pnpm-lock.yaml
- move tsup dep from individual packages to workspace root
- upgrade from 6.7.0 to 8.3.5
=> Update tsup to 8.3.5

apps/ToDoMVC/package.json, apps/dev/package.json, apps/example/package.json, package.json, packages/core/babel-preset-dlight/package.json, packages/core/dlight/package.json, packages/core/store/package.json, packages/core/transpiler/reactivity-parser/package.json, packages/core/transpiler/view-generator/package.json, packages/core/transpiler/view-parser/package.json, packages/tools/babel-plugin-optional-this/package.json, packages/tools/babel-plugin-syntax-typescript-new/package.json, packages/tools/create-dlightjs/package.json, packages/tools/create-dlightjs/tsconfig.json, packages/tools/error-handler/package.json, packages/tools/eslint-plugin-dlight/package.json, packages/tools/vite-plugin-dlight-js/package.json, packages/tools/vite-plugin-dlight/package.json, turbo.json
=> chore: Add tsc typecheck to each package

package.json, packages/core/babel-preset-dlight/package.json, packages/core/dlight/package.json, packages/core/transpiler/reactivity-parser/package.json, packages/core/transpiler/view-generator/package.json, packages/core/transpiler/view-parser/package.json, packages/tools/create-dlightjs/package.json, packages/tools/error-handler/package.json, packages/tools/eslint-plugin-dlight/package.json, packages/tools/vite-plugin-dlight-js/package.json, packages/tools/vite-plugin-dlight/package.json
=> chore: Release 1.0.0

.husky/commit-msg, .husky/pre-commit, commitlint.config.js, package.json, pnpm-lock.yaml
* **PR #107** 👈
* **PR #108**
* **PR #109**
=> chore: update husky

packages/tools/bun-plugin/CHANGELOG.md, packages/tools/bun-plugin/package.json, packages/tools/bun-plugin/src/index.ts, packages/tools/bun-plugin/tsconfig.json
=> feat: create @dlightjs/bun-plugin for transpiling with Bun.build

.changeset/config.json
=> fix: changesets config

packages/tools/bun-plugin/CHANGELOG.md, packages/tools/bun-plugin/package.json
=> chore: release dlight-bun-plugin

.changeset/config.json
=> chore: set changeset config to public

packages/tools/eslint-plugin-dlight/package.json
=> chore: restore eslint-plugin-dlight version

.changeset/little-hotels-design.md, packages/tools/bun-plugin-dlight/CHANGELOG.md, packages/tools/bun-plugin-dlight/package.json
=> chore: release bun-plugin-dlight 0.4

.changeset/little-hotels-design.md, packages/tools/bun-plugin-dlight/CHANGELOG.md, packages/tools/bun-plugin-dlight/README.md, packages/tools/bun-plugin-dlight/package.json
=> feat: add README to bun-plugin-dlight package

packages/tools/bun-plugin-dlight/CHANGELOG.md, packages/tools/bun-plugin-dlight/package.json
=> chore: release bun-plugin-dlight 0.5

packages/tools/bun-plugin-dlight/README.md
=> chore: add reference to bun-static-server in README

packages/core/dlight/src/types/htmlTag/htmlElement.d.ts
=> chore: lint / formatting for htmlElement
